apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: {{ .Release.Name }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 6080
        path: /
