apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: {{ $fullName }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: 6080
        path: /
