apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: ingress-qracknet.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: http
          servicePort: 6080
