apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "template.fullname" . }}
spec:
  rules:
  - host: ingress-qracknet.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: qracknet
          servicePort: 6080
