{{- if .Values.ingress.enabled -}}
{{- $fullName := include "template.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "template.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: ingress-qracknet.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: http
          servicePort: 6080
