apiVersion: v1
kind: Deployment
metadata:
  name: {{ include "template.fullname" . }}
  labels:
{{ include "template.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
